### PR TITLE
Add package json

### PR DESCRIPTION
**Pull request by freizl**
now people could use
- `npm install` to add binaries
- `npm run ...` to build the project

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Would you mind sharing the original motivation behind this?

I'm currently against this for a few reasons but I'm not sure how good these reasons are:
- Why wrap `spago` commands in another tool (e.g. `npm`)? 
- If the issue is that this approach is just that much more convenient, that doesn't strike me as a particularly good argument. I could just as easily copy the current commands into a copy-and-paste format
- This project is licensed under the CC 4.0 NC-BY-SA, but the package.json file says `ISC`.

**Comment by freizl** [comment]
@JordanMartinez 

- The motivation is just simplified the setup process IMHO. UI engineers probably get used to `package.json` & package lock files those days (`package-lock` or `yarn.lock`). Instead of install `spago` and other dependencies globally, I could have all those install locally (within the project) via `npm install`. In other words, it is `much more convenient` essentially and doesn't populate global.
- I wasn't pay attention to the license yet. Will update the license if we decide to move forward the PR.

**Comment by JordanMartinez** [comment]
> I could have all those install locally (within the project) via npm install. In other words, it is much more convenient essentially and doesn't populate global.

Ah, the local installation vs global installation point is a good reason.

Should we instead have two sections for installing things? One for the local installation as this PR proposes and one for the global installation?

I imagine that those who already have PS tools installed globally wouldn't want to install the tools again locally.

Looks like the license field can be updated to `CC-BY-NC-SA-4.0` ([source](https://spdx.org/licenses/)

**Comment by freizl** [comment]
Updated.

**Comment by JordanMartinez** [comment]
Looks good. Thanks!

**Comment by JordanMartinez** [comment]
I'd like to add another CI build to use this particular way of installing things, but I'll leave that for a separate PR/issue.

**Pull request merged**
