### PR TITLE
Broken link: Application Structure

### PR DESCRIPTION
**Pull request by steshaw**

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Thanks for the PR! However, I think the link should point to a tag, not the
`latestRelease` branch. That'll prevent links from breaking in the future.

**Comment by steshaw** [comment]
All the links point to `latestRelease` at the moment :smile:.

**Comment by JordanMartinez** [comment]
Yeah... I thought that might be the case, haha!

**Comment by JordanMartinez** [comment]
Do you want to update all of them to a tag? Otherwise, I can handle this.

**Comment by steshaw** [comment]
Why don't you handled it? I wouldn't know which tag to use :smile:.

**Comment by JordanMartinez** [comment]
Ok! Mind opening an issue for this instead then?

**Comment by JordanMartinez** [comment]
Nevermind about the issue. I referred to this PR, and that's good enough.

**Pull request closed without merging**
